### ISSUE TITLE
Unable to DL sheet

### ISSUE THREAD

**Issue by hostagexii** [odino/docsql#5]
Keep getting the error `Unrecoverable error: The file we downloaded has content type '[text/html; charset=UTF-8]', while we expected 'text/tab-separated-values'. Are you sure you entered the right URL?`

This was working fine last week. Doc URL ends with `/export?format=tsv`

**Comment by odino** [comment]
That generally means the URL is either incorrect or the file is not shared
publicly, so docsql gets the Google doc auth page (html).

**Comment by hostagexii** [comment]
Thank you for pointing me in the right direction. The G Suite admin recently made changes to block public link sharing.
