### ISSUE TITLE
Some tsv files are not accepted in the tool

### ISSUE THREAD

**Issue by yamanmalkoc** [odino/docsql#6]
This tool has been extremely helpful for my job, thank you very much for sharing this publicly. Unfortunately, I started been having an issue with it. Even though I use the correct link to download the table with this URL format:
`https://docs.google.com/spreadsheets/d/<TABLE_ID>/export?format=tsv&gid=<SHEET_GID>`
I get the message 
`Unrecoverable error: The file we downloaded has content type '[text/html; charset=UTF-8]', while we expected 'text/tab-separated-values'. Are you sure you entered the right URL?`

This URL format works for most of the tables but not for some.

When I comment out the part which checks for the table format (tsv) I get this parsing error which might be helpful figuring out the problem we're facing.

`Unrecoverable error: parse error on line 3, column 11: bare " in non-quoted-field`

I checked the table and it doesn't have any character (like ", \t, ',') that might have caused the parsing error. 

Do you have any idea why I might be facing this problem?
I think it might be happening from a redirected link. If a download link is redirected, the downloaded file with `curl` will include the `html` file which will include the redirected link. Is there a way to follow redirections and download the very last file that is reached?

**Comment by odino** [comment]
Hey @yamanmalkoc, I used to have this problem when the file was not shared publicly, or the link wasn't pointing to the tsv export format. Do you have a public link I can use to have a look at the file?

**Comment by yamanmalkoc** [comment]
Thanks for the reply, yes, turns out it is because the file is not shared publicly. Tho I can't make these sheets available to the public. Is there a way to give credentials and authorize the tool to download from a private spreadsheet?

Although it doesn't look like there is an option in the tool which you can give account credentials to access a private spreadsheet.

Do you think that can be added as a feature? I can make a pull request work on such an additional feature if you think that would be valuable. Or I might just do that just for myself if you prefer to keep the code as simple as it is now.

**Comment by odino** [comment]
Unfortunately, you won't be able to use private sheets as of now.

The implementation is fairly trivial but also requires the user to actually login through their google account, making it harder for an automated tool to complete such workflow:

https://developers.google.com/sheets/api/quickstart/go

I've worked in a few companies where most "configuration" data is exposed via Google sheets -- nothing "too" sensitive in there. Of course, if you have a list of employees with salaries it might be a bad idea, but for data that's not sensitive I think making the sheet public is an acceptable trade-off (the link is randomized enough that it would be hard to just guess the URL).

Let me know if I can help with anything else :slightly_smiling_face:

**Comment by odino** [comment]
BTW there might be a chance to access the sheet without the web authorization from the user: https://stackoverflow.com/a/50562013

If you're interested and have some time to write a prototype, I'd be happy to integrate the code back to docsql (just don't have the time to test this method now).

https://developers.google.com/sheets/api/guides/authorizing#APIKey
